apiVersion: v1
kind: Namespace
metadata:
  name: stagging

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-webapp-deployment
  namespace: stagging
  labels:
    app:  e-commerce-webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  e-commerce-webapi
  template:
    metadata:
      labels:
        app:  e-commerce-webapi
    spec:
      containers:
        - name:  e-commerce-webapi-container
          image: daddykiki/e-commerce-webapi #image from docker hub
          ports:
            - containerPort: 3000
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name:  e-commerce-webapi-service
  namespace: stagging
  labels:
    app:  e-commerce-webapi-service
spec:
  selector:
    app:  e-commerce-webapi
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
    
  